### PR TITLE
 - Remove inline from checkboxes (check if this is ok with the params…

### PR DESCRIPTION
**Pull request by ElieBuff**
- Remove inline from checkboxes (check if this is ok with the params section).
 - Remove scrolling.
 - Add margin between graphs.
 - Add margin on the right side also

### CODE REVIEW

**Comment by viebel** [comment]
This is a nice improvement @ElieBuff 
But there are still issues:
1. we need to have a padding at the bottom of the screen
2. we need to have a padding at the right of the screen
3. with the raw data it looks bad (you can view the raw data by pressing pause and then play)

image

**Comment by ElieBuff** [comment]
Padding in the right? 

Why this is needed??

On Sat, 10 Jun 2017 at 23:30 Yehonathan Sharvit

<
mailto:Yehonathan Sharvit <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

This is a nice improvement
https://github.com/eliebuff
But there are still issues:

we need to have a padding at the bottom of the screen

we need to have a padding at the right of the screen

with the raw data it looks bad (you can view the raw data by pressing pause and then play)

https://user-images.githubusercontent.com/955710/27006093-b9da3bc4-4e34-11e7-89af-f16dbb4a71ea.png

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/viebel/vayyar-viz/pull/74#issuecomment-307588534
, or

**Comment by viebel** [comment]
We need padding on the right not to be too close to the edge.

**Comment by viebel** [comment]
@ElieBuff please rebase from develop.
I have fixed a bug in heatmap (thanks to  an automatic test).
Now, the heatmap renders properly without having to press on play/pause.

**Pull request merged**
